name: SnakeGame CI/CD Pipeline

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать workflow при открытии PR в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Шаг 3: Сборка проекта
      - name: Build project
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build  # Зависит от успешного выполнения сборки

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Шаг 3: Запуск тестов
      - name: Run tests
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # Зависит от успешного выполнения сборки и тестов

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Шаг 3: Деплой на удаленный сервер через SSH
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/deploy
            git pull origin main
            ./gradlew build
            java -jar build/libs/snake-game.jar
